/**
 * Portal Front Office - Power Automate Integration Engine
 */
export const AutomationService = {
    // Webhook URL generated by the Microsoft Power Automate HTTP Trigger
    webhookUrl: "YOUR_POWER_AUTOMATE_WEBHOOK_URL_HERE",

    /**
     * Actively triggers a backend workflow flow via HTTP POST fetch.
     * @param {string} actionType - The operational identifier (e.g., 'TRIGGER_DAILY_REPORT')
     * @param {Object} metadata - Contextual data payload from the front office shift
     */
    async triggerFlow(actionType, metadata = {}) {
        const payload = {
            action: actionType,
            timestamp: new Date().toISOString(),
            executedBy: document.getElementById('user-profile-email')?.innerText || "Auditor Front Office",
            hotelLocale: document.documentElement.lang || "pt-PT",
            data: metadata
        };

        try {
            console.log(`[Automation] Initiating fetch handshake for action: ${actionType}...`);

            const response = await fetch(this.webhookUrl, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(payload)
            });

            // Handle HTTP response tokens professionally to avoid silent race condition bugs
            if (response.ok) {
                console.log("[Automation] Execution payload successfully accepted by Power Automate.");
                return { success: true };
            } else {
                const errorText = await response.text();
                console.error(`[Automation] Microsoft Gateway returned status ${response.status}:`, errorText);
                return { success: false, error: `HTTP Error ${response.status}` };
            }

        } catch (error) {
            console.error("[Automation] Network or CORS preflight failure:", error);
            return { success: false, error: "Falha crítica de comunicação com os servidores Microsoft." };
        }
    }
};

/**
 * Initialize active UI event listeners for automation hooks
 */
document.addEventListener('DOMContentLoaded', () => {
    const btnReport = document.getElementById('btn-trigger-report');
    
    if (btnReport) {
        btnReport.addEventListener('click', async (e) => {
            e.preventDefault();

            // UI State Mutation: Prevent Double Submissions/Race Conditions
            const originalText = btnReport.innerText;
            btnReport.innerText = "⏳ A Processar...";
            btnReport.disabled = true;
            btnReport.style.opacity = "0.6";
            btnReport.classList.add('loading-state');

            // Wait for the server handshake explicitly (Patience-driven execution pattern)
            const currentShift = document.querySelector('.duty-manager-value')?.innerText || "Não Definido";
            
            const result = await AutomationService.triggerFlow('TRIGGER_DAILY_REPORT', {
                turno: currentShift,
                observacoes: "Daily Report gerado ativamente através da interface do Portal Web."
            });

            // Revert UI elements safely after response resolution
            btnReport.disabled = false;
            btnReport.style.opacity = "1";
            btnReport.classList.remove('loading-state');
            btnReport.innerText = originalText;

            if (result.success) {
                alert("Sucesso! O Power Automate foi iniciado e o Daily Report está a ser gerado.");
            } else {
                alert(`Falha na Automação: ${result.error}\nAbra a consola de desenvolvimento para analisar.`);
            }
        });
    }
});
