export const translations = {
  pt: {
    // Sidebar/Navigation
    "nav_dashboard": "Dashboard",
    "nav_concierge": "Concierge Virtual",
    "nav_rececao": "Receção",
    "nav_checklist": "Checklist de Turno",
    "nav_caixa": "Contagem de Caixa",
    
    // Header
    "header_title": "Portal Front Office",
    "duty_manager": "Duty Manager:",
    "duty_manager_value": "Tarde / Noite",
    "logout_btn": "Sair",
    
    // Weather
    "weather_loading": "A carregar previsão...",
    "weather_error": "Não foi possível obter a previsão",
    
    // Section Headers
    "hotel_today_title": "Título da secção",
    "hotel_today_desc": "O hotel hoje",
    "stats_budget_desc": "Secção estatísticas e budget - Mês atual",
    "noticias_title": "Notícias",
    "eventos_title": "Eventos",
    "links_title": "Links Úteis",
    
    // KPIs
    "kpi_occupancy": "Ocupação do dia %",
    "kpi_inhouse": "Residentes",
    "kpi_arrivals": "Chegadas",
    "kpi_departures": "Saídas",
    
    // Show Rooms & Status
    "showroom_title": "Show Rooms",
    "status_operational": "Tudo Operacional",
    
    // Budget Table Headers
    "th_stats_revenue": "Estatísticas e Receitas Dia anterior",
    "th_accommodation": "Alojamento",
    "th_total_daily": "Total (diário)",
    "th_budget_daily": "Budget (diário)",
    "th_total_monthly": "Total (mensal)",
    "th_budget_monthly": "Budget (mensal)",
    
    // Budget Category / Row labels
    "row_occupancy": "Ocupação",
    "row_inhouse": "In-House",
    "row_arrivals": "Chegadas",
    "row_departures": "Saídas",
    "row_total_accommodation": "TOTAL ALOJAMENTO",
    "row_room_service": "Room Service",
    "row_pa": "P. A.",
    "row_gastrobar": "Gastrobar",
    "row_bar": "Bar",
    "row_total_fb": "TOTAL F&B",
    "row_laundry": "Lavandaria",
    "row_transfers": "Transferes",
    "row_parking": "Estacionamento",
    "row_spa": "SPA",
    "row_misc": "Diversos",
    "row_phone": "Telefone",
    "row_misc_blackmoon": "Diversos Blackmoon",
    "row_total_annexes": "TOTAL ANEXOS + DIVERSOS",
    "row_grand_total": "TOTAL GERAL",
    
    // Secondary section placeholders
    "no_events": "Sem eventos agendados.",
    "loading_news": "A carregar notícias...",
    "no_news": "Não há notícias disponíveis no momento.",
    
    // Concierge Page
    "concierge_search_placeholder": "Pesquisar guias (ex: táxi, metro, metro aeroporto...)",
    "concierge_categories": "Categorias",
    "category_all": "Todos",
    "category_transports": "Transportes",
    "category_restaurants": "Restaurantes",
    "category_poi": "Pontos de Interesse",
    "category_useful": "Úteis",
    "no_guides_found": "Não foram encontrados guias para a sua pesquisa.",
    
    // Checklist Page
    "checklist_title": "Checklist de Turno",
    "step_1": "Passo 1",
    "step_1_desc": "Seleciona o turno, identifica o rececionista e regista a data antes de abrir a checklist.",
    "new_shift": "Nova abertura de turno",
    "new_shift_note": "Escolhe o turno que vais trabalhar e inicia o processo do zero.",
    "field_shift": "Turno",
    "select_placeholder": "Selecionar...",
    "field_rec_name": "Nome do rececionista",
    "field_rec_name_placeholder": "Ex.: João Silva",
    "field_work_date": "Data de trabalho",
    "field_initial_obs": "Observações iniciais do turno",
    "field_initial_obs_placeholder": "Ex.: pendência de receção, informação do Blackmoon, anomalia de sistema...",
    "btn_start_shift": "Iniciar turno",
    "btn_reset_shift": "Anular e recomeçar",
    "btn_finish_shift": "Finalizar turno",
    "confirm_reset": "Deseja anular o progresso da checklist e voltar ao início? (A contagem de caixa será mantida)",
    "shift_active": "Turno Ativo:",
    "visual_legend": "Legenda visual",
    "legend_optional": "Item opcional / condicional",
    "legend_help": "Botão ? = explicação pedagógica",
    "legend_download": "Item com download associado",
    "shift_conclusion": "Conclusão do turno",
    "field_final_obs": "Observações finais / justificações",
    "field_final_obs_placeholder": "Ex.: itens pendentes justificados, discrepâncias, informação não recebida...",
    "proof_note": "O comprovativo em PDF incluirá auditor, data, protocolo MySana, observações e itens concluídos.",
    "fixed_paths": "Caminhos fixos",
    "daily_closings": "Fechos diários",
    "daily_templates": "Templates diários",
    "all_reports_note": "TODOS OS RELATÓRIOS SALVOS NAS PASTAS DO FECHO DO DIA DEVEM SER EMITIDOS APÓS A AUDITORIA NOTURNA.",
    "bulk_toggle_label": "Marcar / desmarcar todos desta secção",
    "proto_label": "Protocolo MySana",
    "proto_placeholder": "Ex.: MYS-2024-001",
    "msg_proto_required": "O protocolo MySana é obrigatório.",
    "msg_unchecked_warning": "Existem itens obrigatórios não marcados.",
    
    // Caixa (Cash Counting) Page
    "cash_counting_title": "Contagem de Caixa",
    "field_current_shift": "Turno Atual",
    "field_current_rec": "Rececionista Atual",
    "field_next_shift": "Próximo Turno",
    "field_next_rec": "Próximo Rececionista",
    "cash_counting_desc": "Insira as quantidades de moedas e notas, vaucheres e paid-outs do turno.",
    "notes_title": "Notas (€)",
    "coins_title": "Moedas (€)",
    "table_header_denomination": "Valor / Denominação",
    "table_header_qty": "Qtd",
    "table_header_total": "Total",
    "subtotal_notes": "Subtotal Notas:",
    "subtotal_coins": "Subtotal Moedas:",
    "vouchers_title": "Vales (Vouchers)",
    "paidouts_title": "Paid-outs",
    "btn_add_voucher": "+ Adicionar Vale",
    "btn_add_paidout": "+ Adicionar Paid-out",
    "th_value": "Valor (€)",
    "th_justification": "Justificação",
    "th_department": "Departamento",
    "th_room": "Quarto",
    "th_responsible": "Responsável",
    "th_date": "Data",
    "th_actions": "Ações",
    "total_docs": "Total Documentos (Vales + Paid-outs):",
    "fixed_cash_fund": "Fundo de Caixa Fixo: 750.00€",
    "amount_received_system": "Montante recebido dia (Sistema):",
    "grand_total_cash_docs": "Total Geral (Espécie + Docs):",
    "calculated_deposit": "Depósito do Dia:",
    "difference_label": "Diferença:",
    "msg_all_correct": "Tudo certo!",
    "msg_inconsistency": "Inconsistência na contagem",
    "msg_auto_save": "Nota: A contagem de caixa será guardada automaticamente com o progresso do turno.",
    
    // Shifts
    "shift_noite": "Noite",
    "shift_manha": "Manhã",
    "shift_tarde": "Tarde",
    "shift_doorman": "Doorman",
    
    // Missing Keys
    "checklist_subtitle": "Selecione o turno correspondente para carregar as tarefas obrigatórias.",
    "legend_warn": "* Se não assinalar os itens obrigatórios, a linha ficará vermelha ao submeter.",
    "btn_export_pdf": "Exportar Relatório PDF",
    "warn_fill_start": "Por favor, seleciona o turno, preenche o nome do rececionista e a data.",
    "confirm_reset_checklist": "Deseja anular o progresso da checklist e voltar ao início? (A contagem de caixa será mantida)",
    "warn_proto_required": "O protocolo MySana é obrigatório.",
    "warn_mandatory_unchecked": "Existem itens obrigatórios não marcados.",
    "confirm_finish_shift": "Checklist completa. Deseja finalizar o turno, gerar PDF e reiniciar?",
    "warn_pdf_lib_missing": "Biblioteca de PDF não carregada.",
    "check_all_section": "Marcar / desmarcar todos desta secção",
    "cash_status_ok": "Tudo certo!",
    "cash_status_discrepancy": "Inconsistência na contagem",
    "Sem informação": "Sem informação",
    "Ocupação mês até agora": "Ocupação mês até agora",
    "Mês atual": "Mês atual",
    "Mês próximo mês": "Próximo mês",
    "Ocupação": "Ocupação",
    "In-House": "In-House",
    "Chegadas": "Chegadas",
    "Saídas": "Saídas",
    "TOTAL ALOJAMENTO": "TOTAL ALOJAMENTO",
    "Room Service": "Room Service",
    "P. A.": "P. A.",
    "Gastrobar": "Gastrobar",
    "Bar": "Bar",
    "TOTAL F&B": "TOTAL F&B",
    "Lavandaria": "Lavandaria",
    "Transferes": "Transferes",
    "Estacionamento": "Estacionamento",
    "SPA": "SPA",
    "Diversos": "Diversos",
    "Telefone": "Telefone",
    "Diversos Blackmoon": "Diversos Blackmoon",
    "TOTAL ANEXOS + DIVERSOS": "TOTAL ANEXOS + DIVERSOS",
    "TOTAL GERAL": "TOTAL GERAL",
    "ALOJAMENTO": "ALOJAMENTO",
    "F&B": "F&B",
    "DIVERSOS": "DIVERSOS",
    
    // New Report Generator & Archive keys
    "nav_gerar_report": "Gerar Daily Report",
    "nav_reports": "Arquivo de Relatórios",
    "report_title_label": "Gerar Relatório Diário",
    "report_desc_label": "Preencha as métricas operacionais e financeiras do dia para gerar o PDF oficial do hotel e enviá-lo ao SharePoint.",
    "section_kpis": "Métricas Operacionais e KPIs",
    "section_financials": "Receitas e Tarifas Médias",
    "section_vips": "Chegadas VIP",
    "section_events": "Eventos Diários",
    "section_oos": "Quartos Fora de Serviço (OOS)",
    "btn_add_vip": "+ Adicionar VIP",
    "btn_add_event": "+ Adicionar Evento",
    "btn_add_oos": "+ Adicionar Quarto OOS",
    "btn_submit_report": "Gerar e Submeter Relatório",
    "lbl_search": "Pesquisar:",
    "lbl_from": "De:",
    "lbl_to": "Até:",
    "lbl_type": "Tipo:",
    "lbl_all": "Todos",
    "lbl_date": "Data",
    "lbl_name": "Nome",
    "lbl_actions": "Ações",
    "btn_view_pdf": "Ver / Download PDF",
    "msg_unauthorized_admin": "Acesso restrito. Redirecionando para a página principal..."
  },
  en: {
    // Sidebar/Navigation
    "nav_dashboard": "Dashboard",
    "nav_concierge": "Virtual Concierge",
    "nav_rececao": "Reception",
    "nav_checklist": "Shift Checklist",
    "nav_caixa": "Cash Counting",
    
    // Header
    "header_title": "Front Office Portal",
    "duty_manager": "Duty Manager:",
    "duty_manager_value": "Afternoon / Night",
    "logout_btn": "Logout",
    
    // Weather
    "weather_loading": "Loading forecast...",
    "weather_error": "Could not retrieve weather forecast",
    
    // Section Headers
    "hotel_today_title": "Section Title",
    "hotel_today_desc": "The hotel today",
    "stats_budget_desc": "Statistics & Budget - Current Month",
    "noticias_title": "News",
    "eventos_title": "Events",
    "links_title": "Useful Links",
    
    // KPIs
    "kpi_occupancy": "Day Occupancy %",
    "kpi_inhouse": "In-House Guests",
    "kpi_arrivals": "Arrivals",
    "kpi_departures": "Departures",
    
    // Show Rooms & Status
    "showroom_title": "Show Rooms",
    "status_operational": "All Operational",
    
    // Budget Table Headers
    "th_stats_revenue": "Statistics and Revenue Previous Day",
    "th_accommodation": "Accommodation",
    "th_total_daily": "Total (daily)",
    "th_budget_daily": "Budget (daily)",
    "th_total_monthly": "Total (monthly)",
    "th_budget_monthly": "Budget (monthly)",
    
    // Budget Category / Row labels
    "row_occupancy": "Occupancy",
    "row_inhouse": "In-House",
    "row_arrivals": "Arrivals",
    "row_departures": "Departures",
    "row_total_accommodation": "TOTAL ACCOMMODATION",
    "row_room_service": "Room Service",
    "row_pa": "Breakfast",
    "row_gastrobar": "Gastrobar",
    "row_bar": "Bar",
    "row_total_fb": "TOTAL F&B",
    "row_laundry": "Laundry",
    "row_transfers": "Transfers",
    "row_parking": "Parking",
    "row_spa": "SPA",
    "row_misc": "Miscellaneous",
    "row_phone": "Telephone",
    "row_misc_blackmoon": "Miscellaneous Blackmoon",
    "row_total_annexes": "TOTAL ANNEXES + MISC",
    "row_grand_total": "GRAND TOTAL",
    
    // Secondary section placeholders
    "no_events": "No scheduled events.",
    "loading_news": "Loading news...",
    "no_news": "No news available at this moment.",
    
    // Concierge Page
    "concierge_search_placeholder": "Search guides (e.g. taxi, metro, metro airport...)",
    "concierge_categories": "Categories",
    "category_all": "All",
    "category_transports": "Transports",
    "category_restaurants": "Restaurants",
    "category_poi": "Points of Interest",
    "category_useful": "Useful Guides",
    "no_guides_found": "No guides found matching your search.",
    
    // Checklist Page
    "checklist_title": "Shift Checklist",
    "step_1": "Step 1",
    "step_1_desc": "Select the shift, identify the receptionist, and record the date before opening the checklist.",
    "new_shift": "New Shift Opening",
    "new_shift_note": "Choose the shift you will work and start the process from scratch.",
    "field_shift": "Shift",
    "select_placeholder": "Select...",
    "field_rec_name": "Receptionist name",
    "field_rec_name_placeholder": "E.g.: John Doe",
    "field_work_date": "Working date",
    "field_initial_obs": "Initial shift observations",
    "field_initial_obs_placeholder": "E.g.: reception issues, Blackmoon info, system abnormality...",
    "btn_start_shift": "Start shift",
    "btn_reset_shift": "Cancel and restart",
    "btn_finish_shift": "Finish shift",
    "confirm_reset": "Do you want to cancel the checklist progress and return to the start? (Cash count will be preserved)",
    "shift_active": "Active Shift:",
    "visual_legend": "Visual Legend",
    "legend_optional": "Optional / conditional item",
    "legend_help": "Button ? = pedagogical explanation",
    "legend_download": "Item with associated download",
    "shift_conclusion": "Shift Conclusion",
    "field_final_obs": "Final observations / justifications",
    "field_final_obs_placeholder": "E.g.: justified pending items, discrepancies, information not received...",
    "proof_note": "The PDF receipt will include auditor, date, MySana protocol, observations, and completed items.",
    "fixed_paths": "Fixed paths",
    "daily_closings": "Daily closings",
    "daily_templates": "Daily templates",
    "all_reports_note": "ALL REPORTS SAVED IN DAILY CLOSING DIRECTORIES MUST BE GENERATED AFTER NIGHT AUDIT.",
    "bulk_toggle_label": "Check / uncheck all in this section",
    "proto_label": "MySana Protocol",
    "proto_placeholder": "E.g.: MYS-2024-001",
    "msg_proto_required": "MySana Protocol is required.",
    "msg_unchecked_warning": "There are unchecked mandatory items.",
    
    // Shifts
    "shift_noite": "Night",
    "shift_manha": "Morning",
    "shift_tarde": "Afternoon",
    "shift_doorman": "Doorman",
    
    // Caixa (Cash Counting) Page
    "cash_counting_title": "Cash Counting",
    "field_current_shift": "Current Shift",
    "field_current_rec": "Current Receptionist",
    "field_next_shift": "Next Shift",
    "field_next_rec": "Next Receptionist",
    "cash_counting_desc": "Enter the quantity of notes and coins, vouchers, and paid-outs for the shift.",
    "notes_title": "Notes (€)",
    "coins_title": "Coins (€)",
    "table_header_denomination": "Value / Denomination",
    "table_header_qty": "Qty",
    "table_header_total": "Total",
    "subtotal_notes": "Subtotal Notes:",
    "subtotal_coins": "Subtotal Coins:",
    "vouchers_title": "Vouchers",
    "paidouts_title": "Paid-outs",
    "btn_add_voucher": "+ Add Voucher",
    "btn_add_paidout": "+ Add Paid-out",
    "th_value": "Value (€)",
    "th_justification": "Justification",
    "th_department": "Department",
    "th_room": "Room",
    "th_responsible": "Responsible",
    "th_date": "Date",
    "th_actions": "Actions",
    "total_docs": "Total Documents (Vouchers + Paid-outs):",
    "fixed_cash_fund": "Fixed Cash Fund: 750.00€",
    "amount_received_system": "Amount received day (System):",
    "grand_total_cash_docs": "Grand Total (Cash + Docs):",
    "calculated_deposit": "Day's Deposit:",
    "difference_label": "Difference:",
    "msg_all_correct": "All correct!",
    "msg_inconsistency": "Counting inconsistency",
    "msg_auto_save": "Note: Cash count will be saved automatically with the shift progress.",
    
    // Missing Keys
    "checklist_subtitle": "Select the corresponding shift to load mandatory tasks.",
    "legend_warn": "* If you do not check mandatory items, the line will turn red upon submission.",
    "btn_export_pdf": "Export PDF Report",
    "warn_fill_start": "Please select the shift, fill in the receptionist name and the date.",
    "confirm_reset_checklist": "Do you want to cancel the checklist progress and return to the start? (Cash count will be preserved)",
    "warn_proto_required": "MySana Protocol is required.",
    "warn_mandatory_unchecked": "There are unchecked mandatory items.",
    "confirm_finish_shift": "Checklist complete. Do you want to finish the shift, generate PDF and reset?",
    "warn_pdf_lib_missing": "PDF library not loaded.",
    "check_all_section": "Check / uncheck all in this section",
    "cash_status_ok": "All correct!",
    "cash_status_discrepancy": "Counting inconsistency",
    "Sem informação": "No information",
    "Ocupação mês até agora": "Monthly Occupancy to Date",
    "Mês atual": "Current Month",
    "Mês próximo mês": "Next Month",
    "Ocupação": "Occupancy",
    "In-House": "In-House",
    "Chegadas": "Arrivals",
    "Saídas": "Departures",
    "TOTAL ALOJAMENTO": "TOTAL ACCOMMODATION",
    "Room Service": "Room Service",
    "P. A.": "Breakfast",
    "Gastrobar": "Gastrobar",
    "Bar": "Bar",
    "TOTAL F&B": "TOTAL F&B",
    "Lavandaria": "Laundry",
    "Transferes": "Transfers",
    "Estacionamento": "Parking",
    "SPA": "SPA",
    "Diversos": "Miscellaneous",
    "Telefone": "Telephone",
    "Diversos Blackmoon": "Miscellaneous Blackmoon",
    "TOTAL ANEXOS + DIVERSOS": "TOTAL ANNEXES + MISC",
    "TOTAL GERAL": "GRAND TOTAL",
    "ALOJAMENTO": "ACCOMMODATION",
    "F&B": "F&B",
    "DIVERSOS": "MISCELLANEOUS",
    
    // New Report Generator & Archive keys
    "nav_gerar_report": "Generate Daily Report",
    "nav_reports": "Reports Archive",
    "report_title_label": "Generate Daily Report",
    "report_desc_label": "Fill in the operational and financial metrics for the day to generate the official hotel PDF and send it to SharePoint.",
    "section_kpis": "Operational Metrics & KPIs",
    "section_financials": "Revenues & Average Rates",
    "section_vips": "VIP Arrivals",
    "section_events": "Daily Events",
    "section_oos": "Out of Service Rooms (OOS)",
    "btn_add_vip": "+ Add VIP",
    "btn_add_event": "+ Add Event",
    "btn_add_oos": "+ Add OOS Room",
    "btn_submit_report": "Generate & Submit Report",
    "lbl_search": "Search:",
    "lbl_from": "From:",
    "lbl_to": "To:",
    "lbl_type": "Type:",
    "lbl_all": "All",
    "lbl_date": "Date",
    "lbl_name": "Name",
    "lbl_actions": "Actions",
    "btn_view_pdf": "View / Download PDF",
    "msg_unauthorized_admin": "Restricted access. Redirecting to home page..."
  }
};

export function getTranslation(lang, key) {
  const code = (lang || 'pt').toLowerCase().startsWith('en') ? 'en' : 'pt';
  return translations[code][key] || translations['pt'][key] || key;
}

export function translatePage(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const translation = getTranslation(lang, key);
    if (translation) {
      if (el.tagName === 'INPUT' && (el.type === 'text' || el.type === 'search')) {
        el.placeholder = translation;
      } else {
        el.textContent = translation;
      }
    }
  });
}
